#!/usr/bin/env bash
set -u
VERSION="5.0.0"
BASE_URL="https://raw.githubusercontent.com/arnavkingx/Pterodyacal-Installer/main"
C='\033[0;36m';M='\033[0;35m';W='\033[1;37m';G='\033[0;32m';R='\033[0;31m';Y='\033[1;33m';N='\033[0m'
banner(){ clear 2>/dev/null||true; echo; echo -e "${C}╔══════════════════════════════════════════════════╗${N}"; echo -e "${C}║${W}                     APNELY                     ${C}║${N}"; echo -e "${C}║${M}             PTERODACTYL INSTALLER             ${C}║${N}"; echo -e "${C}║${W}              MADE BY ARNAV SHARMA             ${C}║${N}"; echo -e "${C}║${W}                 Version ${VERSION}                ${C}║${N}"; echo -e "${C}╚══════════════════════════════════════════════════╝${N}"; echo; }
ok(){ echo -e "${G}✓${N} $1";}; bad(){ echo -e "${R}✗${N} $1";}; warn(){ echo -e "${Y}!${N} $1";}; pause(){ read -r -p 'Press Enter to continue...' _;}; root(){ [ "$(id -u)" -eq 0]|| { bad 'Run as root.';exit 1;};}
run_remote(){ local f="$1"; local tmp; tmp=$(mktemp "/tmp/apnely-${f}.XXXXXX"); if ! curl -fsSL --retry 3 "${BASE_URL}/${f}" -o "$tmp"; then rm -f "$tmp"; bad "Could not download ${f}"; pause; return 1; fi; chmod 700 "$tmp"; bash "$tmp"; local rc=$?; rm -f "$tmp"; return $rc; }
system_menu(){ while true; do banner; echo 'SYSTEM TOOLS'; echo; echo '  [1] System Information'; echo '  [2] Docker Status'; echo '  [3] Disk Usage'; echo '  [4] Memory Usage'; echo '  [5] Back'; echo; read -r -p 'Select: ' c; case "$c" in 1) banner; . /etc/os-release 2>/dev/null||true; echo "OS: ${PRETTY_NAME:-unknown}"; echo "Kernel: $(uname -r)"; echo "Arch: $(uname -m)"; pause;;2) systemctl status docker --no-pager||true;pause;;3) df -h;pause;;4) free -h;pause;;5)return;;*)bad 'Invalid option';;esac;done; }
main(){ root; command -v curl>/dev/null|| { apt-get update;apt-get install -y curl;}; while true; do banner; echo 'MAIN MENU'; echo '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'; echo '  [1] Pterodactyl Panel'; echo '  [2] Wings'; echo '  [3] Nginx'; echo '  [4] Certbot / SSL'; echo '  [5] System Tools'; echo '  [6] Exit'; echo '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'; read -r -p 'Select option [1-6]: ' c; case "$c" in 1)run_remote panel.sh;;2)run_remote wings.sh;;3)run_remote nginx.sh;;4)run_remote ssl.sh;;5)system_menu;;6)clear;echo -e "${M}APNELY - MADE BY ARNAV SHARMA${N}";exit 0;;*)bad 'Invalid option';;esac;done; }
main
